# Generated by Django 4.2 on 2024-03-25 19:05

from django.db import migrations


def create_user_diet(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    Diet = apps.get_model("diet", "Diet")

    for user in User.objects.all():
        Diet.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0002_diet"),
    ]

    operations = [
        migrations.RunPython(create_user_diet),
    ]
