# Generated by Django 4.2 on 2024-03-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_auto_20240325_1905"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodlog",
            options={"ordering": ("-date", "created_at")},
        ),
    ]
