# Generated by Django 4.2 on 2024-04-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0006_foodlog_meal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="calories",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="food",
            name="carbs",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="food",
            name="fats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="food",
            name="proteins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
